# Generated by Django 2.1.7 on 2019-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_sellwell',
            field=models.BooleanField(default=False),
        ),
    ]
